"""s09 -- Figures & numbers ledger.

Renders the final figures from processed tables and writes docs/numbers_ledger.md,
mapping each article claim to the producing table/cell. Deterministic: no randomness,
re-running yields identical output.

In:  processed/*.parquet, interim/*.parquet
Out: figures/*.png, docs/numbers_ledger.md
"""
from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from src.lib import config


def _save(fig, name):
    path = config.FIGURES / name
    fig.savefig(path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {path}")
    return path


def fig_productivity_by_bucket(prod):
    sub = prod[(prod["dimension"] == "bucket") & (prod["scope"] == "pooled") &
               (prod["metric"] == "goals")].copy()
    sub["b"] = sub["phase_or_bucket"].astype(int)
    sub = sub.sort_values("b")
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.errorbar(sub["b"] * 10, sub["rate"],
                yerr=[sub["rate"] - sub["ci_lo"], sub["ci_hi"] - sub["rate"]],
                fmt="o-", capsize=3)
    ax.set_xlabel("match minute (bucket start)")
    ax.set_ylabel("goals per live-minute")
    ax.set_title("Goal productivity per live-minute by 10-min bucket (pooled)")
    return _save(fig, "f01_productivity_by_bucket.png")


def fig_stoppage_by_state(prod):
    sub = prod[(prod["dimension"] == "state_2H_stoppage") & (prod["scope"] == "pooled") &
               (prod["metric"] == "goals")]
    if sub.empty:
        return None
    fig, ax = plt.subplots(figsize=(6, 5))
    ax.bar(sub["state"], sub["rate"],
           yerr=[sub["rate"] - sub["ci_lo"], sub["ci_hi"] - sub["rate"]], capsize=4)
    ax.set_ylabel("goals per live-minute (2H stoppage)")
    ax.set_title("2H-stoppage goal productivity by state at 90'")
    return _save(fig, "f02_stoppage_by_state.png")


def fig_board_pre_post():
    path = config.PROCESSED / "board_descriptive.parquet"
    if not path.exists():
        return None
    desc = pd.read_parquet(path)
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.bar(desc.index.astype(str), desc["mean"])
    ax.set_ylabel("board added time per match (min)")
    ax.set_title("Board added time: PRE vs POST")
    return _save(fig, "f03_board_pre_post.png")


def fig_lb_vs_board():
    inc_path = config.INTERIM / "incident_stoppage.parquet"
    board_path = config.INTERIM / "board_added_time.parquet"
    if not board_path.exists():
        return None
    inc = pd.read_parquet(inc_path)
    board = pd.read_parquet(board_path)
    matches = pd.read_parquet(config.INTERIM / "matches.parquet")
    lb = inc.groupby("match_id")["lower_bound_s"].sum() / 60
    bd = board.groupby("match_id")["board_min"].sum()
    grp = matches.set_index("match_id")["group"]
    df = pd.DataFrame({"lb": lb, "board": bd, "group": grp}).dropna()
    fig, ax = plt.subplots(figsize=(6, 6))
    for g, c in (("PRE", "tab:blue"), ("POST", "tab:orange")):
        d = df[df["group"] == g]
        ax.scatter(d["board"], d["lb"], s=14, alpha=0.6, label=g, color=c)
    lim = max(df["board"].max(), df["lb"].max()) + 1
    ax.plot([0, lim], [0, lim], "k--", lw=1, label="y=x")
    ax.set_xlabel("board added time (min)")
    ax.set_ylabel("incident lower bound (min)")
    ax.set_title("Lower bound vs board added time")
    ax.legend()
    return _save(fig, "f04_lb_vs_board.png")


def fig_sensitivity():
    path = config.PROCESSED / "counterfactual_summary.parquet"
    if not path.exists():
        return None
    s = pd.read_parquet(path)
    s = s[s["group"] == "all"].sort_values("pct_changed")
    fig, ax = plt.subplots(figsize=(8, max(4, 0.3 * len(s))))
    ax.errorbar(s["pct_changed"], range(len(s)),
                xerr=[s["pct_changed"] - s["ci_lo"], s["ci_hi"] - s["pct_changed"]],
                fmt="o", capsize=3)
    ax.set_yticks(range(len(s)))
    ax.set_yticklabels(s["knob_set"], fontsize=7)
    ax.set_xlabel("% of matches changed")
    ax.set_title("Counterfactual sensitivity grid (95% CI)")
    return _save(fig, "f05_sensitivity_grid.png")


def write_ledger(prod):
    lines = ["# Numbers ledger", "",
             "Every article figure -> producing table + cell. Regenerated by s09.", ""]

    def cell(scope, dim, metric, key, state="all"):
        m = prod[(prod["scope"] == scope) & (prod["dimension"] == dim) &
                 (prod["metric"] == metric) & (prod["phase_or_bucket"] == str(key)) &
                 (prod["state"] == state)]
        if m.empty:
            return "n/a"
        r = m.iloc[0]
        return f"{r['rate']:.4f} [{r['ci_lo']:.4f}, {r['ci_hi']:.4f}] (n={r['n_events']:.0f}, live_min={r['live_minutes']:.1f})"

    lines += [
        "## Productivity (goals per live-minute, pooled)",
        f"- 2H stoppage: `{cell('pooled','phase','goals','2H_stoppage')}` "
        "-> processed/productivity.parquet (scope=pooled,dimension=phase,phase=2H_stoppage,metric=goals)",
        f"- regular play: `{cell('pooled','phase','goals','regular')}` -> same table, phase=regular",
        f"- 2H stoppage, tied at 90: `{cell('pooled','state_2H_stoppage','goals','2H_stoppage','tied')}`",
        f"- 2H stoppage, non-tied: `{cell('pooled','state_2H_stoppage','goals','2H_stoppage','non_tied')}`",
        "",
    ]

    cf = config.PROCESSED / "counterfactual_summary.parquet"
    if cf.exists():
        s = pd.read_parquet(cf)
        allg = s[s["group"] == "all"]
        lo, hi = allg["pct_changed"].min(), allg["pct_changed"].max()
        lines += [
            "## Headline counterfactual (X%)",
            f"- range across sensitivity grid: {lo:.1%} - {hi:.1%} "
            "-> processed/counterfactual_summary.parquet (group=all)",
            "- LOCK the chosen central knob_set + CI in docs/decisions.md before publishing.",
            "",
        ]
    else:
        lines += ["## Headline counterfactual", "- (run s08 first)", ""]

    (config.DOCS / "numbers_ledger.md").write_text("\n".join(lines))
    print(f"  wrote {config.DOCS / 'numbers_ledger.md'}")


def main() -> None:
    config.ensure_dirs()
    prod = pd.read_parquet(config.PROCESSED / "productivity.parquet")
    fig_productivity_by_bucket(prod)
    fig_stoppage_by_state(prod)
    fig_board_pre_post()
    fig_lb_vs_board()
    fig_sensitivity()
    write_ledger(prod)
    print("  s09 complete.")


if __name__ == "__main__":
    main()
